@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/products

###
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "Fork",
    "description": "Fork description",
    "purchasePrice": 30,
    "salesPrice": 30,
    "stock": 3
}
