@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/clients

###
GET {{baseUrl}}/clients/31121a80-0bff-449c-89fb-972fb23fdd4c

###
POST {{baseUrl}}/clients
Content-Type: application/json

{
    "name": "Lucian",
    "email": "lucian@xpto.com",
    "document": "1234-5678",
    "address": {
        "street": "Rua 123",
        "number": "99",
        "complement": "Casa Verde",
        "city": "Criciúma",
        "state": "SC",
        "zipCode": "88888-888"
    }
}
